// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskTracker.Api.Data;

#nullable disable

namespace TaskTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskTracker.Api.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Assignee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Assignee = "Alex",
                            DueDate = new DateTime(2026, 8, 16, 4, 26, 3, 606, DateTimeKind.Utc).AddTicks(5545),
                            Priority = 2,
                            Status = 2,
                            Title = "Setup PostgreSQL database"
                        },
                        new
                        {
                            Id = 2,
                            Assignee = "Maria",
                            DueDate = new DateTime(2026, 8, 17, 4, 26, 3, 606, DateTimeKind.Utc).AddTicks(5553),
                            Priority = 2,
                            Status = 1,
                            Title = "Design React Dashboard"
                        },
                        new
                        {
                            Id = 3,
                            Assignee = "Sam",
                            DueDate = new DateTime(2026, 8, 18, 4, 26, 3, 606, DateTimeKind.Utc).AddTicks(5554),
                            Priority = 1,
                            Status = 0,
                            Title = "Implement CORS Headers"
                        },
                        new
                        {
                            Id = 4,
                            Assignee = "Alex",
                            DueDate = new DateTime(2026, 8, 19, 4, 26, 3, 606, DateTimeKind.Utc).AddTicks(5555),
                            Priority = 0,
                            Status = 0,
                            Title = "Write Unit Tests"
                        },
                        new
                        {
                            Id = 5,
                            Assignee = "Maria",
                            DueDate = new DateTime(2026, 8, 20, 4, 26, 3, 606, DateTimeKind.Utc).AddTicks(5557),
                            Priority = 2,
                            Status = 0,
                            Title = "Deploy Application"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
